### ISSUE TITLE
Any possibility that this SDK be expo-compatible in the future ?

### ISSUE THREAD

**Issue by BenStirrup** [complycube/complycube-react-native-sdk#3]
Hello,

As there is no discussion enable for this repository, I allowed myself to use the issues' functionality.

Could this SDK be compatible with the expo framework in the future ?

Thank you.

**Comment by ccnasro** [comment]
Hello Ben, and thanks for your suggestion, 

The compatibility of the SDK with the Expo framework is on our Backlog; it will be released in the next few weeks.
You'll be notified once it's released

Thanks,
